config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Acesso negado."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "Usuário atualizado."
    else
      redirect_to users_path, :alert => "Liberado para atualizar usuário."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "Usuário excluido."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Acesso negado."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
           <% if product.id == 1 %>
        <img class="img-responsive img-border img-left" src= "http://media-cdn.tripadvisor.com/media/photo-s/07/4a/c0/47/sassa-sushi.jpg"alt=""%>
                <% elsif product.id == 2 %>
        <img class="img-responsive img-border img-left" src= "https://s3.amazonaws.com/static.ifood.com.br/imagens/ce/pratos/10964/10964_15150813_HotCamaro10.jpg"alt=""%>
                <% elsif product.id == 3 %>
        <img class="img-responsive img-border img-left" src= "http://www.saikoolounge.com.br/wp-content/uploads/2013/01/Hossomaki-Shake-Make.jpg"alt=""%>
                <% elsif product.id == 4 %>
        <img class="img-responsive img-border img-left" src= "http://gynsushi.com.br/delivery/wp-content/uploads/2014/08/Sushi-Kani.jpg"alt=""%>
                <% elsif product.id == 5 %>
        <img class="img-responsive img-border img-left" src= "http://chowasushi.com.br/images/makisushi.png"alt=""%>
                <% elsif product.id == 6 %>
        <img class="img-responsive img-border img-left" src= "https://rodandoemsp.files.wordpress.com/2010/05/dsc00552.jpg"alt=""%>
                <% elsif product.id == 7 %>
        <img class="img-responsive img-border img-left" src= "https://img.peixeurbano.com.br/?img=https://s3.amazonaws.com/pu-mgr/default/a0RG000000aMMxUMAW/54b7a956e4b048ccbf7968e7.jpg&w=620&h=400"alt=""%>
                <% elsif product.id == 8 %>
        <img class="img-responsive img-border img-left" src= "http://jbchost.com.br/grj/img/galerias/japengo_04.jpg"alt=""%>
                <% elsif product.id == 9 %>
        <img class="img-responsive img-border img-left" src= "http://receitasedicasrapidas.com/wp-content/uploads/2015/01/fazer-sashimi-Salmao-1.jpg"alt=""%>
               <% elsif product.id == 10 %>
        <img class="img-responsive img-border img-left" src= "http://meijisushi.com.br/wp-content/uploads/Sashimi-Tako-Polvo-988x741.jpg"alt=""%>
               <% elsif product.id == 11 %>
        <img class="img-responsive img-border img-left" src= "http://gnt.estaticos.tv.br/migracao/fckeditor/image/Temaki-Salmao-Cream-Cheese6.jpg"alt=""%>
               <% elsif product.id == 12 %>
        <img class="img-responsive img-border img-left" src= "http://kikoni.com.br/uploads/cardapio/imagens/102/grande/temaki-philadelfia.png"alt=""%>
                <% elsif product.id == 13 %>
        <img class="img-responsive img-border img-left" src= "http://www.nankinsushi.com.br/uploads-quati/files/54090_album_271.jpg"alt=""%>
                <% elsif product.id == 14 %>
        <img class="img-responsive img-border img-left" src= "http://www.chinainbox.com.br/Fotos_China/tradicionais/images/yakisoba_classico.png"alt=""%>
                <% elsif product.id == 15 %>
        <img class="img-responsive img-border img-left" src= "http://www.chinainbox.com.br/Fotos_China/tradicionais/images/yakisoba_de_camarao.png"alt=""%>

     <% end %>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Preço Unitário: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Atualizar Quantidade", class: "btn btn-primary" %>
              <%= link_to "Deletar", order_item, { data: { confirm: "Você realmente quer excluir '#{order_item.product.name}' do seu carrinho de compras?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Valor total: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    Seu carrinho está vazio no momento. Por favor <%= link_to "volte", root_path %> e adicione algum item nele.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/carts/show.html.slim
h1 Carts#show
p Find me in app/views/carts/show.html.slim

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Itens no Carrinho ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <p>Copyright &copy; Sushi Gama 2015</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Footer -->
<header>
    <div class="container">
        <div class="row">
            <%= render 'layouts/navigation' %>
        </div>
    </div>
</header>

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Editar Conta', edit_user_registration_path %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Criar Conta', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Usuários', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <%= link_to 'Business Casual', root_path, class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
    <%= link_to 'Início', root_path %>
</li>
<li>
    <%= link_to 'Sobre', page_path('about') %>
</li>
<li>
    <%= link_to 'Cardápio', products_path('index') %>
</li>
<li>
    <%= link_to 'Contato', page_path('contact') %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sushi Gama" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div>
        <h1 class="address-bar"><%= render 'layouts/cart_text' %></h1>
      </div>
      <div class="brand">Sushi Gama</div>
      <div class="address-bar">Águas Claras | Taguatinga Shopping | Praça de Alimentação</div>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Teste2'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Teste2'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/order_items/create.html.slim
h1 OrderItems#create
p Find me in app/views/order_items/create.html.slim

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.slim
h1 OrderItems#destroy
p Find me in app/views/order_items/destroy.html.slim

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.slim
h1 OrderItems#update
p Find me in app/views/order_items/update.html.slim

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/pages/about.html.erb
<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Um pouco de
                    <strong>Sushi Gama</strong>
                </h2>
                <hr>
            </div>
            <div class="col-md-6">
                <img class="img-responsive img-border-left" src="http://kirosushi.com.br/wp-content/uploads/2015/07/kiro2-1030x664.jpg" alt="">
            </div>
            <div class="col-md-6">
                <p>Fruto de um sonho, <strong>Sushi Gama</strong> fora fundado no fim de 2015 por dois grandes empreendedores, Lucas Andrade e Matheus Figueiredo.</p>
                <p>Mesmo em tempos de crise, ambos acreditaram em seu potencial e decidiram abrir uma pequena loja de venda de sushi. Contudo, percebendo a saturação do mercado nesse ramo propuseram um diferencial: o Delivery. Destaque esse que permitiu o crescimento rápido da empresa, onde dentro de 6 meses abriram mais três filiais além de 300% de aumento no quadro de funcionários.</p>
                <p>Mas nada disso seria suficiente se ambos não acreditassem em sua força de vontade e na paixão que têm pelo produto vendido.</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Nossa
                    <strong>Equipe</strong>
                </h2>
                <hr>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://imageshack.com/a/img903/8586/e2dV7V.jpg" alt="">
                <h3>Lucas Andrade
                    <small>Diretor</small>
                </h3>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://www.sanmichel.com.br/sky/images/sushiman.png" alt="">
                <h3>Sam Kimura
                    <small>Chef Sushiman</small>
                </h3>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://imageshack.com/a/img908/1386/ST06nF.jpg" alt="">
                <h3>Matheus Figueiredo
                    <small>Diretor</small>
                </h3>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/pages/blog.html.erb
<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Company
                    <strong>blog</strong>
                </h2>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-1.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-2.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-3.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
            </div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/pages/contact.html.erb
<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Contatos
                    <strong>Sushi Gama</strong>
                </h2>
                <hr>
            </div>
            <div class="col-md-8">
                <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
            </div>
            <div class="col-md-4">
                <p>Telefone:
                    <strong>123.456.7890</strong>
                </p>
                <p>Email:
                    <strong><a href="mailto:sushigama@sushi.com">sushigama@sushi.com</a></strong>
                </p>
                <p>Endereço:
                    <strong>Praça de Alimentação - 3º Piso
                        <br>Águas Claras, Taguatinga Shopping</strong>
                </p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Fale
                    <strong>conosco</strong>
                </h2>
                <hr>
                <p>Dúvidas? Reclamações? Sugestões? Críticas? Elogios? Bad? Fale conosco, teremos o maior prazer em respondê-lo!</p>
                <form role="form">
                    <div class="row">
                        <div class="form-group col-lg-4">
                            <label>Nome</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Endereço de Email</label>
                            <input type="email" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Número de Telefone</label>
                            <input type="tel" class="form-control">
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-lg-12">
                            <label>Mensagem</label>
                            <textarea class="form-control" rows="6"></textarea>
                        </div>
                        <div class="form-group col-lg-12">
                            <input type="hidden" name="save" value="contact">
                            <button type="submit" class="btn btn-default">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/products/index.html.erb
<h3 class="text-center">Produtos a Venda</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/index.html.slim
h1 Products#index
p Find me in app/views/products/index.html.slim

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Deletar usuário", user_path(user), :data => { :confirm => "Tem certeza?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="box">
    <h3>Usuários</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
   </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>